// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BancoInicial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BancoInicial1));
        
        string IMigrationMetadata.Id
        {
            get { return "201705310238442_BancoInicial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
